###
# Get all sailors
GET http://localhost:8080/sailors

###
# Get a specific sailor
GET http://localhost:8080/sailors/0442949d-7db8-4a70-a167-e7c258d7692a

###
# Create a new sailor
POST http://localhost:8080/sailors
Content-Type: application/json

{
  "firstName": "Rick",
  "lastName": "Doe",
  "email": "rick@sailor.com"
}